apiVersion: apps/v1
kind: Deployment
metadata:
  name: rigup-deployment-frontend
  namespace: fpro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rigupapp
  template:
    metadata:
      labels:
        app: rigupapp
        type: frontend
    spec:
      containers:
      - name: rigup-cont-backend
        image: abitsugar/rigup_frontend:tagVersion
      - containerPort: 80
